### PR TITLE
Updated to Oxmysql 1.18.1

### PR DESCRIPTION
**Pull request by SkylarPlayz348**
Just making the update

### CODE REVIEW

**Comment by BerkieBb** [comment]
Jezus, 1.18.1, are you in the future?

**Comment by SkylarPlayz348** [comment]
Nope my txAdmin said there was an update and it's true

**Comment by SkylarPlayz348** [comment]
I may have put the wrong version but it's still the update

**Comment by BerkieBb** [comment]
I was joking, you made a typo, it's not 1.18.1 but 1.8.1

**Comment by SkylarPlayz348** [comment]
Ya it's 1.8.1 in the code I was half asleep while typing the title lol

**Pull request closed without merging**
