### PR TITLE
Test recipe for NPWD

### PR DESCRIPTION
**Pull request by GhzGarage**

### CODE REVIEW

**Comment by FuryRomania** [comment]
test

**Comment by FuryRomania** [comment]
hello

**Comment by jazzyduster** [comment]
yo yo wasup

**Review by jeann2013 — APPROVED** [review]

**Comment by jeann2013** [comment]
I tested this resource works fine

**Comment by NylanderrDK** [comment]
Works fine for us as well.

**Review by NylanderrDK — APPROVED** [review]

**Pull request closed without merging**
